import 'package:flutter/material.dart';
import '../controllers/gift_controller.dart';
import '../controllers/gift_details_controller.dart';
import '../auth_service.dart';
import '../models/gift.dart';

class GiftDetailsPage extends StatefulWidget {
  final String eventId;
  final Map<String, dynamic>? existingGift;
  final String autogeneratedId;

  GiftDetailsPage({
    required this.eventId,
    required this.autogeneratedId,
    this.existingGift,
  });

  @override
  _GiftDetailsPageState createState() => _GiftDetailsPageState();
}

class _GiftDetailsPageState extends State<GiftDetailsPage> {
  final GiftDetailsController _controller = GiftDetailsController();
  final GiftController _giftController = GiftController();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  String _selectedEventId = '';
  List<Map<String, dynamic>> _events = [];
  String _selectedStatus = 'Available';
  bool _isLoading = true; // For showing loading indicator while fetching events

  @override
  void initState() {
    super.initState();
    _loadEvents();
    _initializeForm();
  }

  // Fetch events from Firebase
  Future<void> _loadEvents() async {
    final userId = AuthService.getCurrentUser()?.uid;
    if (userId != null) {
      final events = await _giftController.loadEventsForUser(userId);
      setState(() {
        _events = events;
        if (widget.eventId.isNotEmpty) _selectedEventId = widget.eventId;
        _isLoading = false; // Stop loading once events are fetched
      });
    }
  }

  // Initialize form if editing an existing gift
  void _initializeForm() {
    if (widget.existingGift != null) {
      _controller.giftNameController.text = widget.existingGift!['name'] ?? '';
      _controller.categoryController.text = widget.existingGift!['category'] ?? '';
      _controller.descriptionController.text = widget.existingGift!['description'] ?? '';
      _controller.priceController.text = widget.existingGift!['price']?.toString() ?? '0.0';
      _selectedStatus = widget.existingGift!['status'] ?? 'Available';
    }
  }

  // Save or update gift
  void _saveGift() async {
    if (_formKey.currentState!.validate() && _selectedEventId.isNotEmpty) {
      // Safely retrieve input values and provide defaults
      final String name = _controller.giftNameController.text.trim().isNotEmpty
          ? _controller.giftNameController.text.trim()
          : "Unnamed Gift";

      final String category = _controller.categoryController.text.trim().isNotEmpty
          ? _controller.categoryController.text.trim()
          : "No Category";

      final String description = _controller.descriptionController.text.trim().isNotEmpty
          ? _controller.descriptionController.text.trim()
          : "No Description";

      final double price = double.tryParse(_controller.priceController.text.trim()) ?? 0.0;

      final String status = _selectedStatus.isNotEmpty ? _selectedStatus : "Available";

      // Validate and get the gift ID
      final String giftId = widget.existingGift != null
          ? widget.existingGift!['id'] ?? ''
          : widget.autogeneratedId;

      if (giftId.isEmpty) {
        // If ID is empty, print error and exit
        print("Error: Gift ID is empty!");
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: Invalid gift ID.")),
        );
        return;
      }

      // Ensure isPledged value defaults to false if not provided
      final bool isPledged = widget.existingGift?['isPledged'] ?? false;

      // Construct the Gift object
      final newGift = Gift(
        id: giftId,
        name: name,
        category: category,
        status: status,
        description: description,
        price: price,
        isPledged: isPledged, eventId: '',
      );

      print("Saving Gift:");
      print("ID: ${newGift.id}");
      print("Name: ${newGift.name}");
      print("Category: ${newGift.category}");
      print("Description: ${newGift.description}");
      print("Price: ${newGift.price}");
      print("Status: ${newGift.status}");
      print("isPledged: ${newGift.isPledged}");

      try {
        if (widget.existingGift != null) {
          // Update existing gift
          await _giftController.updateGiftInEvent(_selectedEventId, newGift);
          print("Gift updated successfully!");
        } else {
          // Add a new gift
          await _giftController.addGiftToEvent(_selectedEventId, newGift);
          print("Gift added successfully!");

          // Clear the form after adding
          _controller.giftNameController.clear();
          _controller.categoryController.clear();
          _controller.descriptionController.clear();
          _controller.priceController.clear();
          setState(() {
            _selectedStatus = 'Available';
          });
        }

        Navigator.pop(context, true); // Close the page and refresh the list
      } catch (e) {
        print("Error saving gift: $e");
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Failed to save the gift. Please try again.")),
        );
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Please fill all fields and select an event.")),
      );
    }
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingGift != null ? "Edit Gift" : "Add New Gift"),
        backgroundColor: Colors.brown,
        foregroundColor: Colors.white,
      ),
      body: Stack(
        children: [
          // Background image
          Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('assets/bg5.jpeg'),
                fit: BoxFit.cover,
              ),
            ),
          ),
          SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Container(
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.brown, width: 2),
                  borderRadius: BorderRadius.circular(8),
                  color: Colors.white.withOpacity(0.8),
                ),
                child: Form(
                  key: _formKey,
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Event Name', style: _formLabelStyle),
                        _isLoading
                            ? Center(child: CircularProgressIndicator())
                            : DropdownButtonFormField<String>(
                          value: _selectedEventId.isNotEmpty
                              ? _selectedEventId
                              : null,
                          decoration: InputDecoration(),
                          items: _events.map((event) {
                            return DropdownMenuItem<String>(
                              value: event['id'],
                              child: Text(event['name']),
                            );
                          }).toList(),
                          onChanged: (value) {
                            setState(() {
                              _selectedEventId = value!;
                            });
                          },
                          validator: (value) =>
                          value == null ? 'Please select an event' : null,
                        ),
                        SizedBox(height: 10),
                        _buildTextField('Gift Name', _controller.giftNameController),
                        _buildTextField('Description', _controller.descriptionController),
                        _buildTextField('Category', _controller.categoryController),
                        _buildTextField('Price', _controller.priceController,
                            isNumeric: true),
                        SizedBox(height: 10),
                        Text('Status', style: _formLabelStyle),
                        DropdownButtonFormField<String>(
                          value: _selectedStatus,
                          decoration: InputDecoration(),
                          items: ['Available', 'Pledged'].map((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(value),
                            );
                          }).toList(),
                          onChanged: (String? newValue) {
                            setState(() {
                              _selectedStatus = newValue!;
                            });
                          },
                        ),
                        SizedBox(height: 20),
                        Center(
                          child: SizedBox(
                            width: double.infinity,
                            child: ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.brown,
                                foregroundColor: Colors.white,
                              ),
                              onPressed: _saveGift,
                              child: Text('Save Gift'),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  TextStyle get _formLabelStyle => TextStyle(
    color: Colors.black,
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );

  Widget _buildTextField(String label, TextEditingController controller,
      {bool isNumeric = false}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: _formLabelStyle),
        TextFormField(
          controller: controller,
          keyboardType: isNumeric ? TextInputType.number : TextInputType.text,
          decoration: InputDecoration(),
          validator: (value) => value!.isEmpty ? 'Please enter $label' : null,
        ),
        SizedBox(height: 10),
      ],
    );
  }
}
