name: project_hedieaty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.1
  path: ^1.8.3

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg2.jpg
    - assets/bg2.jpeg
    - assets/p3.jpeg
    - assets/bg3.jpeg
    - assets/p2.jpeg
    - assets/p1.jpeg
    - assets/bg4.jpeg
    - assets/bg5.jpeg
    - assets/profile.jpg
